#!/bin/bash

if [ -z "$1" ]; then
  echo "Give me a tag to build, please." >&2
  exit 1
fi

docker build -t discourse/filebeat-config:$1 .

if [ -n "$PUSH" ]; then
  docker push discourse/filebeat-config:$1
fi
